### ISSUE TITLE
Project Red - Compatibility

### ISSUE THREAD

**Issue by Eurymachus** [SlimeVoid/LittleBlocks-FML#20]
Need a full test on this to determine what is the issue, (Also need to test with versions for 1.6)
Currently:
- BlockLamp crashes on getIcon, which uses tile.getColour, which returns Index out of bounds error 16 (max is 15)

**Comment by Dushess** [comment]
Will write here for now, the issue is multiparts and little chunks cannot be placed in same chunk in 1.7.\* because it causes renderer error and CTD.
Tested on 1.7.10.
I can create an issue with more info if needed.
